(defun my-term/term-send-backward-kill-word ()
  (interactive)
  (term-send-raw-string "\e\C-?"))
(defun my-term/term-send-undo ()
  (interactive)
  (term-send-raw-string "\C-_"))
(defun my-term/term-send-ctrl-z ()
  (interactive)
  (term-send-raw-string "\C-z"))
(defun my-term/term-send-ctrl-x ()
  (interactive)
  (term-send-raw-string "\C-x"))
(defun my-term/term-send-shift-tab ()
  (interactive)
  (term-send-raw-string "\e[Z"))
(defun my-term/toggle-mode ()
  (interactive)
  (if (term-in-line-mode)
      (term-char-mode)
    (term-line-mode)))
